### ISSUE TITLE
No subscriber to the marker in ROS Kinetic

### ISSUE THREAD

**Issue by aronmeszaros** [philip-long/cable_driven_robot#2]
Warning is shown when running rviz:
[ WARN] [1552305656.392927707]: Please create a subscriber to the marker [ INFO] [1552305657.366858025]: rviz version 1.12.16 [ INFO] [1552305657.366913036]: compiled against Qt version 5.5.1 [ INFO] [1552305657.366926942]: compiled against OGRE version 1.9.0 (Ghadamon) [ WARN] [1552305657.393191069]: Please create a subscriber to the marker [ WARN] [1552305658.393492676]: Please create a subscriber to the marker [ WARN] [1552305659.393806111]: Please create a subscriber to the marker [ WARN] [1552305660.393908187]: Please create a subscriber to the marker [ WARN] [1552305661.394266060]: Please create a subscriber to the marker [ WARN] [1552305662.394463241]: Please create a subscriber to the marker [ WARN] [1552305663.394631315]: Please create a subscriber to the marker [ WARN] [1552305665.960964757]: Please create a subscriber to the marker [ WARN] [1552305666.961086766]: Please create a subscriber to the marker [ INFO] [1552305667.300184243]: Stereo is NOT SUPPORTED [ INFO] [1552305667.310154298]: OpenGl version: 2.1 (GLSL 1.2).

**Comment by philip-long** [comment]
Is "Please create a subscriber to the marker" been continuously published or just at the beginning? This warning means that there is no subscriber to the topic "visualization_marker". It's normal that its printed a couple of times at the beginning before the subscriber is latched but if you can see the robot, all is well. 

Is the gui issue still occuring?

**Comment by aronmeszaros** [comment]
it is shown a few times at the beginning, then Rviz launches nicely and no more warnings are shown after that; so it is normal, good to know, thank you 👍 

By the way, the gui works fine, the joint positions are published and the robot moves and rotates as it should, however I am wondering how the transformation part should work because whatever positions and orientations i put into the fields the numbers go crazy and the robot starts to fly around even if I put 0 or 0.0 everywhere for the rotation and even if I put in the exactly same position values it has once achieved by altering the cables. It doesn't go crazy only if its current position and rotation is fed in, then it sits calmly :)
<img width="1440" alt="Screenshot 2019-03-11 at 12 04 56" src="https://user-images.githubusercontent.com/32513673/54146065-79da1d80-442f-11e9-99af-4c57c01554df.png">

**Comment by philip-long** [comment]
I'll have a look towards the end of the week, we've a big demo coming up so I don't have much time at the moment.

**Comment by philip-long** [comment]
So I had a quick look and it happens on my version as well, which is weird :(

It's been a while since I looked at this code but as I remember  the rviz robot was created to show a real CDPR, but a bit of a hack was added to "simulate" it. To do so a desired position creates a change in cable length which is sent to the robot, the returning joint values are integrated to find the new Cartesian position. However,  in "simulation" the integration is creating numerical instabilities.

 If you're working entirely in simulation I would **highly** recommend having a look at https://github.com/darwinlau/CASPR by Darwin Lau's team which includes dynamics and is much more powerful.

**Comment by aronmeszaros** [comment]
I see, thank you for the explanation and for your time, I'll have a closer look at the repo you mentioned but will still stick to parts of your code because we are planning to deploy our project with components from B&R either way :) just wanted to make sure the code works 👍

**Comment by philip-long** [comment]
No problem. We successfully used this to communicate with the B&R motors for joint position and torque control. Just a heads up, though, when doing this we had a second program running on the B&R which parses the xml code.
